container:
  image: golang:latest

test_task:
  tests_script:
   - go version
   # vet
   - go vet ./*/
   # test
   - go test -cover -race ./*/
   # bench
   - go test -bench=. -benchmem ./*/
  build_script:
    # build
    - go build ./*/

