container:
  image: golang:latest

test_task:
  tests_script:
   - go version
   - go get github.com/iwdgo/testingfiles
   # vet
   - cd ./binedit
   - go vet
   - cd ../modulo37
   - go vet
   - cd ../sumofconverts
   - go vet
   # test
   - cd ../binedit
   - go test -cover -race
   - cd ../modulo37
   - go test -cover -race
   - cd ../sumofconverts
   - go test -cover -race
   # bench
   - cd ../binedit
   - go test -bench=.
   - cd ../modulo37
   - go test -bench=.
   - cd ../sumofconverts
   - go test -bench=. -benchmem
  build_script:
    # build
    - cd ./binedit
    - go build
    - cd ../modulo37
    - go build
    - cd ../sumofconverts
    - go build

