language: go

go:
  - 1.11.x
  # TODO Fails as notation ./... is unusable
  - 1.x

before_install:
  - go get -t -v ./...
  - go vet ./...

script:
  - go test -race -covermode=atomic ./...
  - go test -bench=. ./...
