name: Go
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Vet
        run: go vet ./*/

      - name: Install
        run: go install ./*/

      - name: Test
        run: go test -cover -coverprofile=coverage.out -covermode=atomic -race ./*/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Benchmark
        run: |
          go test -bench=. -benchmem ./*/
