name: Go
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Complete Go set up
        shell: bash
        run: |
          mkdir -p $(go env GOCACHE)
          mkdir -p $(go env GOMODCACHE)
          mkdir -p $(dirname $(go env GOENV))
          mkdir -p $(go env GOPATH)/bin
          echo $PATH

      - name: Vet
        run: go vet ./*/

      - name: Install
        run: go install ./*/

      - name: Test
        run: |
          mkdir coverage
          go test -cover -coverprofile=./coverage/binedit.out -covermode=atomic -race ./binedit
          go test -cover -coverprofile=./coverage/modulo.out -covermode=atomic -race ./modulo37
          go test -cover -coverprofile=./coverage/sumofconverts.out -covermode=atomic -race ./sumofconverts

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/

      - name: Benchmark
        run: |
          go test -bench=. -benchmem ./binedit
          go test -bench=. -benchmem ./modulo37
          go test -bench=. -benchmem ./sumofconverts

