name: Go
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13
          check-latest: true

      - name: Go get dependencies
        run: go get github.com/iwdgo/testingfiles

      - name: Vet
        run: go vet ./*/

      - name: Build
        run: go build ./*/

      - name: Test
        run: |
          mkdir coverage
          cd ./binedit
          go test -cover -coverprofile=../coverage/binedit.out -covermode=atomic -race
          cd ../modulo37
          go test -cover -coverprofile=../coverage/modulo.out -covermode=atomic -race
          cd ../sumofconverts
          go test -cover -coverprofile=../coverage/sumofconverts.out -covermode=atomic -race

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/

      - name: Benchmark
        run: go test -bench=. -benchmem  ./*/

