name: Go
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13
          check-latest: true

      - name: Get dependencies
        run: go get ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -cover -coverprofile=coverage.out -covermode=atomic -race ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Benchmark
        run: go test -bench=. ./...
